spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/afanty_test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root

# es配置类
elasticsearch:
  host: 127.0.0.1
  port: 9200

# 用于控制是否开启Swagger，生产环境记得关闭Swagger，将值设置为 false
springfox:
  swagger2:
    enabled: true

