server:
  port: 9000
  tomcat:
    uri-encoding: UTF-8
    threads:
      max: 500
  servlet:
    context-path: /afanty/base/test
  max-http-header-size: 4048576

spring:
  profiles:
    active: test
  application:
    name: afanty_base_test #服务名称
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    dbcp2:
      initial-size: 1
      min-idle: 3
      max-total: 20
      max-wait-millis: 60000
      time-between-eviction-runs-millis: 60000  # 间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 30000 # 一个连接在池中最小生存的时间，单位是毫秒
      test-while-idle: false
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true  # 打开PSCache

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false # 是否控制台 print mybatis-plus 的 LOGO，默认true
    db-config:
      id-type: assign_uuid  # 主键生成策略
      logic-delete-field: is_delete # 逻辑删除的字段
      logic-delete-value: 1 # 逻辑删除的值，默认1，调用删除api时修改is_delete=1
      logic-not-delete-value: 0 # 逻辑未删除值，默认0，查询时只查is_delete=0的数据
      table-underline: true # 表名是否使用驼峰转下划线命名,只对表名生效，默认true
  configuration:
    # 配置返回数据库(column下划线命名&&返回java实体是驼峰命名)，自动匹配无需as（没开启这个，SQL需要写as： select user_id as userId）
    map-underscore-to-camel-case: true
    LOGGER-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出sql语句
  check-config-location: true # 启动时是否检查 MyBatis XML 文件的存在，默认false

#附件下载
ftpServer:
  #IP|端口|用户名|密码|远程路径|ftp类型
  maps: "{
         	Q: '192.168.30.118|21|root|root|/var/ftp|ftp',
         	Q1: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Q2: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
            X: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Z1: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Z2: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Z: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	U: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	U0: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	V: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp',
         	Y: '192.168.30.118|21|ftpusr|123456|/var/ftp|ftp'
         }"
  saveDir: contact

# okhttp3配置
ok:
  http:
    connect-timeout: 30
    read-timeout: 30
    write-timeout: 30
    # 连接池中整体的空闲连接的最大数量
    max-idle-connections: 200
    # 连接空闲时间最多为 300 秒
    keep-alive-duration: 300
