spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/afanty_test?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root

# es配置类
elasticsearch:
  host: 127.0.0.1
  port: 9200

# 用于控制是否开启Swagger，生产环境记得关闭Swagger，将值设置为 false
springfox:
  swagger2:
    enabled: false

# zookeeper配置
zookeeper:
  cluster: 192.168.30.101:2181,192.168.30.102:2181,192.168.30.103:2181
  timeout: 4000

# FTP
ftp:
  host: 192.168.30.101
  port: 21
  account: ftpuser
  password: ftpuser


